Translate guides/models/relationships.md
DazzlingFugu/ember-fr-guides-source pull request #209
Opened 2023-11-12 16:43 UTC by Jasonlgrd

Closes https://github.com/DazzlingFugu/ember-fr-guides-source/issues/87

2023-11-12 16:47 UTC, Jasonlgrd commented
Some snippets were updated with the code formatter, i pushed it but idk if it's a good idea 😅

2023-11-12 19:39 UTC, MrChocolatine reviewed
Thanks a lot for your contribution, we greatly appreciate.

Please don't be scared about the number of comments I made, most of them are the same (putting English terms in _italic_ , typing errors, ...) while others are "real suggestions" with more content.

Besides, this high number is also due to how the original text is formatted, with sentences split over several lines... ¯\_(ツ)_/¯

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +de noms de relations séparés par des virgules.
```suggestion
Quand vous récupérez des données depuis le serveur pour un modèle qui a une relation avec
un ou plusieurs autres modèles, vous voudrez peut-être récupérer les _records_ liés à ces modèles
en même temps. Par exemple, lors de la récupération d'un article de blog, vous voulez aussi
peut-être accéder aux commentaires associés à l'article. La spécification [JSON:API](https://jsonapi.org/format/#fetching-includes)
permet aux serveurs d'accepter un paramètre de requête, via la clé `include`, en tant que
requête afin d'inclure ces _records_ liés dans la réponse retournée aux clients.
La valeur du paramètre doit être une liste de noms de relations, séparés par des virgules.
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Si vous utilisez un adaptateur qui support JSON:API, comme celui par défaut d'Ember [`JSONAPIAdapter`](https://api.emberjs.com/ember-data/release/classes/JSONAPIAdapter), vous pouvez facielement ajou
```suggestion
Si vous utilisez un adaptateur qui supporte JSON:API, comme celui par défaut d'Ember [`JSONAPIAdapter`](https://api.emberjs.com/ember-data/release/classes/JSONAPIAdapter), vous pouvez facilement ajouter le paramètre `include` aux requêtes serveur créé par les méthodes `findRecord()`, `findAll()`,
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +également les commentaires de ce message. Comme ça&nbsp;:
```suggestion
Chacune des méthodes `findRecord()` et `findAll()` acceptent un argument `options` dans
lequel vous pouvez spécifier le paramètre `include`.
Par exemple, prenons un modèle `post` (article) qui a une relation `hasMany` avec le modèle `comment` (commentaire),
lors de la récupération d'un article spécifique, nous pouvons demander au serveur de renvoyer
également les commentaires de cet article. Comme ça&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Le commentaire de l'article serait alors disponible dans votre template comme `model.comments`.
```suggestion
Les commentaires de l'article seraient alors disponibles dans votre template via `model.comments`.
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +commentaires, la requête serait de la forme suivante&nbsp;:
```suggestion
Les relations imbriquées peuvent être spécifiées dans le paramètre `include`, sous la forme
d'une liste de noms de relations, séparés par des points.
Ainsi, pour récupérer à la fois les commentaires de l'article et les auteurs de ces
commentaires, la requête ressemblerait à ça&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Par exemple&nbsp;:
```suggestion
Chacune des méthodes `query()` et `queryRecord()` acceptent un argument `query` qui est directement
sérialisé dans les paramètres de l'URL et le paramètre `include` peut faire partie de cet argument.
Par exemple&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +### Mise à jour des records existants
To keep things consistent with the other titles, how they "speak to the reader".

```suggestion
### Mettre à jour des _records_ existants
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Parfois nous voudrons définir des relatons sur des records déjà existants. Nous pouvons simplement définir une relation `belongsTo`&nbsp;:
```suggestion
Parfois nous voulons définir des relations sur des _records_ déjà existants. Nous pouvons simplement définir une relation `belongsTo`&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Alternativement, nous pourrions mettre à jour la relation `hasMany` en définissant un record dans la relation&nbsp;:
```suggestion
Ou bien, nous pourrions mettre à jour la relation `hasMany` en définissant un _record_ dans la relation&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +### Suppression des relations
To keep things consistent.

```suggestion
### Supprimer des relations
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Il est également possible de supprimer un record depuis la relation `hasMany`&nbsp;:
```suggestion
Il est également possible de supprimer un _record_ d'une relation `hasMany`&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +Par exemple, si nous devions travailler sur les commentaires asynchrones d'un article de blog, nous devrions attendre que la promesse se réalise&nbsp;:
```suggestion
Par exemple, si nous devions travailler sur les commentaires asynchrones d'un article de blog, nous devrions attendre que la promesse soit résolue&nbsp;:
```

2023-11-12 19:39 UTC, MrChocolatine commented on guides/models/relationships.md
> +EmberData requête le serveur pour obtenir les records appropriés et réaffiche le modèle une fois les données reçues.
```suggestion
EmberData interrogera le serveur pour obtenir les _records_ appropriés et régénérera le template une fois les données reçues.
```

2023-11-12 19:40 UTC, MrChocolatine requested changes
Wrong click with my previous review.

2023-11-28 17:03 UTC, BlueCutOfficial commented
@Jasonlgrd thanks a lot for the PR. Could you please add `!guides/models/relationships.md` to the file `.remarkignore` then run `npm run lint` to do the spellcheck :) 

(I added this step in the new contributing guide I am working on, you've been faster than me :D)

2023-11-28 17:23 UTC, Jasonlgrd commented
> @Jasonlgrd thanks a lot for the PR. Could you please add `!guides/models/relationships.md` to the file `.remarkignore` then run `npm run lint` to do the spellcheck :)
> 
> (I added this step in the new contributing guide I am working on, you've been faster than me :D)

Yes I can ! I have run `npm run lint` and he say me I have written `associtation` instead of `association` ^^

Just, how I can ignore when the word is specific ? 
![image](https://github.com/DazzlingFugu/ember-fr-guides-source/assets/35960493/be96b814-99a9-4b97-89f2-5ad02443f731)

2023-11-28 18:22 UTC, BlueCutOfficial commented
You need to add words like `one-to-one`, `many-to-many`, and `Paypal` to the file called `.local.dic`. I don't know why they have both lowercase and uppercase versions in the English file but if it's the same context I would go for simplifying and go only with lowercase everywhere.

2023-11-28 19:51 UTC, MrChocolatine requested changes
High number of comments BUT 97% of them are for the exact same typo. I tried to merge the suggestions as much as possible but again, due to how the text is formatted... We end up with a high number of micro suggestions.

I think I have caught all the typo, but please triple-check on your side as well, it is needed.

The rest of the 3% is just commas, plural, ...

In the future, I recommend that, once you think document is complete/fully translated, copy and paste its content into a Google Document (or whatever you prefer) with the spellchecker enabled, this will highlight what is wrong (or potentially wrong), and other small stuff.

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Maintenant nous pouvons soit mettre à jour la associtation `belongsTo` dans notre nouveau commentaire, soit mettre à jour la associtation `hasMany` de l'article de blog. Comme vous pouvez le constate
Same typo.

```suggestion
Maintenant nous pouvons soit mettre à jour l'association `belongsTo` dans notre nouveau commentaire, soit mettre à jour l'association `hasMany` de l'article de blog. Comme vous pouvez le constater, nous n'avons pas besoin de mettre à jour à la fois `hasMany` et `belongsTo`, EmberData le fera pour nous.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Cela créera un nouveau _record_ `comment` et le sauvegardera sur le serveur. EmberData mettra aussi mettre à jour `myBlogPost` en incluant notre commentaire nouvellement créé dans la associtation `co
Typo + Same typo.

```suggestion
Cela créera un nouveau _record_ `comment` et le sauvegardera sur le serveur. EmberData mettra aussi à jour `myBlogPost` en incluant notre commentaire nouvellement créé dans l'association `comments`.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Dans le cas ci-dessus, la nouvelle associtation `belongsTo` du commentaire sera automatiquement définie à l'article de blog parent.
Same typo again.

```suggestion
Dans le cas ci-dessus, la nouvelle association `belongsTo` du commentaire sera automatiquement définie à l'article de blog parent.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Bien que `createRecord` soit assez simple, la seule chose à laquelle il faut faire attention est que vous ne pouvez actuellement pas assigner une promesse comme associtation.
Same typo.

```suggestion
Bien que `createRecord` soit assez simple, la seule chose à laquelle il faut faire attention est que vous ne pouvez actuellement pas assigner une promesse comme association.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +La valeur du paramètre doit être une liste de noms de associations, séparés par des virgules.
```suggestion
La valeur du paramètre doit être une liste de noms d'associations, séparés par des virgules.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Parfois nous voulons définir des associations sur des _records_ déjà existants. Nous pouvons simplement définir une associtation `belongsTo`&nbsp;:
Same typo.

```suggestion
Parfois nous voulons définir des associations sur des _records_ déjà existants. Nous pouvons simplement définir une association `belongsTo`&nbsp;:
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +### Supprimer des associtations
Same typo.

```suggestion
### Supprimer des associations
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Pour supprimer une associtation `belongsTo`, nous pouvons la définir à `null`, ce qui la supprimera aussi du côté de `hasMany`&nbsp;:
Same typo.

```suggestion
Pour supprimer une association `belongsTo`, nous pouvons la définir à `null`, ce qui la supprimera aussi du côté de `hasMany`&nbsp;:
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Il est également possible de supprimer un _record_ d'une associtation `hasMany`&nbsp;:
Same typo.

```suggestion
Il est également possible de supprimer un _record_ d'une association `hasMany`&nbsp;:
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Comme dans les exemples précédents, la associtation `belongsTo` du commentaire sera également effacée par EmberData.
Same typo.

```suggestion
Comme dans les exemples précédents, l'association `belongsTo` du commentaire sera également effacée par EmberData.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +### Les associtations en tant que promesses
Same typo.

```suggestion
### Les associations en tant que promesses
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Lorsque nous travaillons avec des associtations, il est important de se souvenir qu'elles retournent des promesses.
Same typo.

```suggestion
Lorsque nous travaillons avec des associations, il est important de se souvenir qu'elles retournent des promesses.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +La même chose s'applique aux associtations `belongsTo` :
Same typo.

```suggestion
La même chose s'applique aux associations `belongsTo` :
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +En premier, regardons comment définir la associtation `belongsTo` dans notre nouveau commentaire&nbsp;;
Same typo.

```suggestion
En premier, regardons comment définir l'association `belongsTo` dans notre nouveau commentaire&nbsp;;
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +La seconde manière de faire la même chose est de lier les deux _records_ ensemble en mettant à jour de la associtation `hasMany` de blogPost, comme montré ci-dessous&nbsp;:
Same typo.

```suggestion
La seconde manière de faire la même chose est de lier les deux _records_ ensemble en mettant à jour l'association `hasMany` de blogPost, comme montré ci-dessous&nbsp;:
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Cependant, vous pouvez facilement définir la associtation une fois que la promesse est résolue&nbsp;:
Same typo.

```suggestion
Cependant, vous pouvez facilement définir l'association une fois que la promesse est résolue&nbsp;:
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Ou bien, nous pourrions mettre à jour la associtation `hasMany` en définissant un _record_ dans la associtation&nbsp;:
Same typo.

```suggestion
Ou bien, nous pourrions mettre à jour l'association `hasMany` en définissant un _record_ dans l'association&nbsp;:
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +### Données imbriqués en lecture seule
Féminin.

```suggestion
### Données imbriquées en lecture seule
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Si vous utilisez un adaptateur qui supporte JSON:API, comme celui par défaut d'Ember [`JSONAPIAdapter`](https://api.emberjs.com/ember-data/release/classes/JSONAPIAdapter), vous pouvez facilement ajou
Féminin + pluriel.

```suggestion
Si vous utilisez un adaptateur qui supporte JSON:API, comme celui par défaut d'Ember [`JSONAPIAdapter`](https://api.emberjs.com/ember-data/release/classes/JSONAPIAdapter), vous pouvez facilement ajouter le paramètre `include` aux requêtes serveur créées par les méthodes `findRecord()`, `findAll()`,
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Chacune des méthodes `findRecord()` et `findAll()` acceptent un argument `options` dans
```suggestion
Chacune des méthodes `findRecord()` et `findAll()` accepte un argument `options` dans
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +Chacune des méthodes `query()` et `queryRecord()` acceptent un argument `query` qui est directement
```suggestion
Chacune des méthodes `query()` et `queryRecord()` accepte un argument `query` qui est directement
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +car `blogPost` est la seule associtation de ce modèle.
Same typo.

```suggestion
EmberData fera de son mieux pour découvrir quelles associations sont liées les unes aux autres.
Par exemple, dans le code _one-to-many_ ci-dessus, EmberData comprend que
modifier la relation `comments` doit aussi mettre à jour l'association `blogPost` à l'inverse,
car `blogPost` est la seule association de ce modèle.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +peuvent être indiquées en utilisant `{ inverse: null }`.
Same typo.

```suggestion
Cependant, parfois vous pouvez avoir plusieurs `belongsTo`/`hasMany` pour
le même type. Vous pouvez spécifier quelle propriété du modèle lié est l'inverse
en utilisant l'option `inverse` sur `belongsTo` ou `hasMany`. Les associations sans inverse
peuvent être indiquées en utilisant `{ inverse: null }`.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +il n'y a pas de associtation inverse alors vous pouvez mettre l'inverse à `null`.
Same typo.

```suggestion
Quand vous voulez définir une association réflexive (un modèle qui a une association
avec lui-même), vous devez explicitement définir l'inverse de l'association. S'il
n'y a pas d'association inverse alors vous pouvez mettre l'inverse à `null`.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +devoir définir de modèles superflus.
Same typo + féminin et pluriel.

```suggestion
Certains modèles peuvent avoir des propriétés qui sont des objets de données profondément
imbriqués en lecture seule. La solution naïve serait de définir
un modèle pour chaque objet imbriqué et utiliser `hasMany` et `belongsTo` pour
créer l'association imbriquée. Cependant, puisque les données en lecture seule n'auront
jamais besoin d'être mises à jour et sauvegardées, cela aboutit souvent à la création
d'une grande quantité de code pour très peu d'avantages. Une approche alternative est de
définir cette association en utilisant un attribut sans transformation (`@attr`). Cela
simplifie l'accès aux valeurs en lecture seule des autres objets et templates sans
devoir définir de modèles superflus.
```

2023-11-28 19:51 UTC, MrChocolatine commented on guides/models/relationships.md
> +commentaires, la requête ressemblerait à ça&nbsp;:
Same typo.

```suggestion
Les associations imbriquées peuvent être spécifiées dans le paramètre `include`, sous la forme
d'une liste de noms d'associations, séparés par des points.
Ainsi, pour récupérer à la fois les commentaires de l'article et les auteurs de ces
commentaires, la requête ressemblerait à ça&nbsp;:
```

2023-11-28 19:53 UTC, MrChocolatine commented on guides/models/relationships.md
>  ### One-to-One
@BlueCutOfficial what do you think?

2023-12-05 14:52 UTC, BlueCutOfficial commented on guides/models/relationships.md
>  ### One-to-One
I like the idea, we could give this translation at least once. Your suggestion matches the little I remember about SQL relationships, works for me :)

I don't have a strong opinion about using French everywhere or giving a translation once with the _One-to-one_ (association de type (1,1)) syntax.

2023-12-06 15:24 UTC, MrChocolatine commented on guides/models/relationships.md
>  ### One-to-One
> I don't have a strong opinion about using French everywhere or giving a translation once with the One-to-one (association de type (1,1)) syntax.

Yes, not necessarily every time but at least once, like in this (main) chapter.

2023-12-16 13:38 UTC, MrChocolatine approved these changes

2023-12-18 20:42 UTC, MrChocolatine commented on .local.dic
> +one-to-one
https://github.com/DazzlingFugu/ember-fr-guides-source/blob/90aa6f17b3ed98cf3e8771567fa9a761868b3d89/CONTRIBUTING.md?plain=1#L46

2024-01-03 08:26 UTC, BlueCutOfficial commented on .local.dic
> +one-to-many
```suggestion
one-to-many
```

2024-01-03 08:27 UTC, merged